# Loader Metadata
modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/alcatrazEscapee/primal-winter/issues"

[[mods]]
    modId = "primalwinter"
    version = "${file.jarVersion}"
    displayName = "Primal Winter"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/primalwinter"
    logoFile="logo.png"
    authors = "AlcatrazEscapee"
    description = '''
        A horrible accident has left the world - the entire world - a frozen wasteland. Unending snowstorms rage across the land, from forests, to plains, to jungles, to deserts. The air is thick with fog and wind howls across the landscape. Will you be able to survive in this primordial winter?
        '''

[[dependencies.primalwinter]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.primalwinter]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,)"
    ordering = "NONE"
    side = "BOTH"
